/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import db.GafanhotoDAO;

/**
 *
 * @author Wagner Carestini
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        boxNewSexo.removeAllItems();
        boxNewSexo.addItem("MASCULINO");
        boxNewSexo.addItem("FEMININO");
        boxNewSexo.addItem("PREFIRO NÃO DIZER");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        txtNewLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnVoltaLogin = new javax.swing.JButton();
        btnCriarCadastro = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        boxNewSexo = new javax.swing.JComboBox<>();
        spnNewIdade = new javax.swing.JSpinner();
        lblTest = new javax.swing.JLabel();
        LblTestIdade = new javax.swing.JLabel();
        lblTestLogin = new javax.swing.JLabel();
        lblTestNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 430));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 40, -1));

        jLabel2.setText("Sexo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel3.setText("Idade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel4.setText("Login:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 40, -1));

        txtNewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtNewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 110, -1));

        txtNewLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtNewLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CADASTRO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 82, 263, 58));

        btnVoltaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnVoltar.png"))); // NOI18N
        btnVoltaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 25, 20));

        btnCriarCadastro.setText("Cadastrar");
        btnCriarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCriarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton2.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnFechar.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 20));

        boxNewSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxNewSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNewSexoActionPerformed(evt);
            }
        });
        jPanel1.add(boxNewSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, -1));

        spnNewIdade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 105, 1));
        jPanel1.add(spnNewIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 111, -1));

        lblTest.setText("jLabel6");
        jPanel1.add(lblTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        LblTestIdade.setText("jLabel6");
        jPanel1.add(LblTestIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        lblTestLogin.setText("jLabel7");
        jPanel1.add(lblTestLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        lblTestNome.setText("jLabel8");
        jPanel1.add(lblTestNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewNameActionPerformed

    private void txtNewLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewLoginActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void btnVoltaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        new TelaInicial().setVisible(true);
    }//GEN-LAST:event_btnVoltaLoginActionPerformed

    private void boxNewSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNewSexoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boxNewSexoActionPerformed

    private void btnCriarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarCadastroActionPerformed
        // TODO add your handling code here:
        String nome = txtNewName.getText();
        int idade = Integer.parseInt(spnNewIdade.getValue().toString());
        String sexo = boxNewSexo.getSelectedItem().toString();
        String login = txtNewLogin.getText();
        GafanhotoDAO.cadastrar(nome, idade, sexo, login);
    }//GEN-LAST:event_btnCriarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTestIdade;
    private javax.swing.JComboBox<String> boxNewSexo;
    private javax.swing.JButton btnCriarCadastro;
    private javax.swing.JButton btnVoltaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblTestLogin;
    private javax.swing.JLabel lblTestNome;
    private javax.swing.JSpinner spnNewIdade;
    private javax.swing.JTextField txtNewLogin;
    private javax.swing.JTextField txtNewName;
    // End of variables declaration//GEN-END:variables
}
